logging.level.remitly.task.stockmarket=DEBUG
logging.level.org.springframework.web=INFO
logging.level.org.hibernate.SQL=DEBUG
logging.level.org.hibernate.orm.jdbc.bind=TRACE

management.tracing.sampling.probability=1.0