logging.level.remitly.task.stockmarket=INFO
logging.level.org.springframework.web=WARN
logging.level.org.hibernate.SQL=WARN
logging.level.org.hibernate.orm.jdbc.bind=WARN

management.tracing.sampling.probability=0.1