logging.level.remitly.task.stockmarket=INFO
logging.level.org.springframework.web=WARN
logging.level.org.hibernate.SQL=WARN
logging.level.org.hibernate.orm.jdbc.bind=WARN

management.tracing.sampling.probability=0.01

management.endpoint.health.show-details=never
management.zipkin.tracing.endpoint=http://zipkin:9411/api/v2/spans
management.endpoint.health.show-details=never